import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Autogenerated by Vite
// Modified by Ronald Zhang but it's mostly all AI generated fixes

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3001,
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },
  css: {
    transformer: 'postcss',
  },
  build: {
    cssMinify: 'esbuild',
  },
});
